name: me_voy_usuario
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dio: ^4.0.6
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  geolocator: ^8.0.1
  flutter_native_splash: ^2.1.1
  provider: ^6.0.3
  connectivity_plus: ^2.3.5
  internet_connection_checker: ^1.0.0+1
  flutter_map: ^1.1.1
  latlong2: ^0.8.0
  cached_network_image: ^3.2.0
  flutter_polyline_points: ^1.0.0
  sliding_up_panel: ^2.0.0+1
  polyline_codec: ^0.1.6
  file: ^6.1.4
  fluttertoast: ^8.0.9
  animate_do: ^2.1.0
  flutter_local_notifications: ^14.1.1
  firebase_messaging: ^14.6.4
  firebase_core: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets: 
    - assets/
    - assets/images/
  uses-material-design: true
flutter_native_splash:
 color: "#FFFFFF"
 image: "assets/images/bus.png"